"""Draws the Sip and Surf character (a pixel portrait of ayush) into assets/character-sprite.png.

Run from the repo root:  python3 tools/make_character.py   (needs Pillow)
Each letter in the grid is one pixel; the palette below maps letters to colours.
"""
from pathlib import Path

from PIL import Image
G = r"""
..............KK..KK................
.........KK.KKHHKKHHK.KK............
........KHHKHHHHHHhHHKHHK...........
.......KHHHHHhHHHHHHHHHHHK..........
......KHHhHHHHHHHhHHHHHhHHK.........
......KHHHHHHHHHHHHHHHHHHHHK........
.....KHHHHHHhHHHHHHHHHHHHHHHK.......
......KHHHHHHHHHHHHHHHHHHHHHHK......
......KHHHHHHHHHHSHHHHHHHSHHK.......
.......KHHHHHHHSSHSSSSSHHSSSK.......
.......KHHHHHHSSSSSSSSSSSSSSK.......
.......KHHHHSSSSSSSKGGGKSKGGGK......
.......KHHHSSSrrbbKGGgGGKKGGgGK.....
.......KHHHSsSSSSSKGGGGGKSKGGGGK....
.......KHHHSsSSSSSSKGGGKSSSKGGGSK...
........KHSSSSSSSSSSSSSSSSSSSSSK....
........KsSSSSSSSSSSSSSSSSmmmSSK....
.........KsSSSSSSSSSSSSSSSSMMSK.....
..........KKssSSSSSSSSSSSSSKK.......
............KJJJJJJJJJJJJK..........
...........KJJJJJJJjJJJJJJK.........
.........KKJJJJJJJJjJJJJJJJKK.......
......KKKAAJJJJJJJJjJJJJJJJJJK......
.....KDDKAAJJJJJJJJjJJJJJJJJJJK.....
.....KDDKAAJJJJJJJJjJJJwwwwJJJK.....
.....KDDKAAJJJJJJJJjJJJJJJJJJJJK....
.....KDDKAAJJJJJJJJjJJJJJKJJJJJK....
.....KDDKAAJJJJJJJJjJJJJKJJJJJJK....
.....KDDKAAJJJJJJJJjJJJJKJJJJJJK....
.....KDDKAAJJJJJJJJjJJJJKJJJJJJKKKK.
.....KDDKAAJJJJJJJJjJJJJKJJJJJKCCCCK
......KKKAAJJJJJJJJjJJJJKJJJJJKCCCCK
........KAAJJJJJJJJjJJJJKJJJJKSSBBBK
........KJJJJJJJJJJjJJJJJKdJKSSSLLBK
........KJJJJJJJJJJjJJJJJKddKSSSLLBK
........KJJJJJJJJJJjJJJJJJKKsSSKLLBK
........KJJJJJJJJJJjJJJJJJJK.KKBLLBK
........KdJJJJJJJJJjJJJJJJdK..KBLLBK
.........KddddddddddddddddK...KBBBBK
.........KPPPPPPPPPPPPPPPPK....KKKK.
.........KPPPPPPPPpPPPPPPPK.........
.........KPPPPPPPKKKPPPPPPK.........
.........KPPPPPPPK.KPPPPPPK.........
.........KPPPPPPPK.KPPPPPPK.........
.........KpPPPPPPK.KpPPPPPK.........
.........KPPPPPPPK.KPPPPPPK.........
........KXXXXXXXK..KXXXXXXXXK.......
........KXXXXXXXXK.KXXXXXXXXXK......
........KZZZZZZZZK.KZZZZZZZZZK......
.........KKKKKKKK...KKKKKKKKK.......
"""
P = {
 'K':(22,18,26),'H':(44,32,26),'h':(62,47,38),'m':(120,80,52),'S':(178,125,86),'s':(143,85,48),
 'G':(18,13,12),'g':(90,92,105),'r':(211,58,44),'b':(58,123,213),'M':(126,56,43),
 'J':(47,44,51),'j':(30,28,33),'d':(28,26,30),'w':(232,230,236),'A':(138,138,143),'D':(95,95,100),
 'P':(42,49,64),'p':(29,35,48),'X':(58,58,62),'Z':(230,230,230),
 'B':(205,238,252),'L':(58,167,232),'C':(30,90,160),
}
rows=[r for r in G.strip('\n').split('\n')]
W=max(len(r) for r in rows); H=len(rows)
for i,r in enumerate(rows):
    if len(r)!=W: print('row',i,len(r))
im=Image.new('RGBA',(W,H),(0,0,0,0))
for y,r in enumerate(rows):
    for x,c in enumerate(r.ljust(W,'.')):
        if c!='.': im.putpixel((x,y),P[c]+(255,))
out = Path(__file__).resolve().parent.parent / 'assets' / 'character-sprite.png'
im.save(out)
print(f'Wrote {out} ({W} x {H})')
